/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	SystemInit();
	char str[32];
	int choice;
	UartInit(9600);
	LedInIt(GPIO_RED);
	LedInIt(GPIO_BLUE);



	while(1){
	UartPuts("Enter your choice\r\n");
	UartPuts("1.Red Led ON\r\n2.Red Led OFF\r\n3.Blue Led ON\r\n4.Blue Led OFF\r\n");
	UartGets(str);
	sscanf(str, "%d", &choice);
	UartPuts(str);
	switch(choice){
	case 1:LedOn(GPIO_RED);
		break;
	case 2:LedOff(GPIO_RED);
			break;
	case 3:LedOn(GPIO_BLUE);
			break;
	case 4:LedOff(GPIO_BLUE);
			break;
	}
	}
	return 0;
}





