/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"
#include "accel.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	LIS_Data val;
	SystemInit();
	LIS_InIt();
	LedInIt(GPIO_ORANGE);
	LedInIt(GPIO_RED);
	LedInIt(GPIO_BLUE);
	LedInIt(GPIO_GREEN);

	while(1){
		if(LIS_IsDataAvail()){
			val=LIS_GetData();
			if(val.x>=3500)
				LedOn(GPIO_RED);

			else
				LedOff(GPIO_RED);




			if(val.x<=-3500)
				LedOn(GPIO_GREEN);

			else
				LedOff(GPIO_GREEN);



			if(val.y>=3500)
			 LedOn(GPIO_ORANGE);

			else
			LedOff(GPIO_ORANGE);



			if(val.y<=-3500)
			LedOn(GPIO_BLUE);

			else
			LedOff(GPIO_BLUE);

		}
	}


	return 0;
}
