/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"
#include "timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	Timer_InIt();

	LedInIt(GPIO_BLUE);
	LedInIt(GPIO_RED);
	LedInIt(GPIO_ORANGE);
	LedInIt(GPIO_GREEN);
	Timer_InIt();
	while(1){
		for(int i=0;i<3;i++){
		LedOn(GPIO_GREEN+i);
		Timer_Delay(3000);
		LedOff(GPIO_GREEN+i);
		Timer_Delay(7000);
		}

	}
	return 0;
}
